//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vJAXB 2.1.10 in JDK 6 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2011.07.13 at 11:48:35 PM IST 
//

@javax.xml.bind.annotation.XmlSchema(namespace = "http://www.cleartrip.com/air/", elementFormDefault = javax.xml.bind.annotation.XmlNsForm.QUALIFIED)
package in.theqwerty.travel.flight.beans.xml.jaxb;
